#!/bin/bash

echo "🚀 Starting infrastructure (Postgres & pgAdmin)..."
docker-compose up -d

echo "⏳ Waiting for database..."
sleep 3

echo "🔥 Starting FastAPI application (Hot-Reload enabled)..."
./venv/bin/uvicorn app.main:app --reload --host 0.0.0.0 --port 8001
