"""add_payment_midtrans_fields

Revision ID: 367bd79b288e
Revises: 924fd8fc0808
Create Date: 2026-04-06 10:14:55.779430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '367bd79b288e'
down_revision: Union[str, None] = '924fd8fc0808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('snap_token', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('payment_url', sa.String(length=500), nullable=True))
    op.add_column('payments', sa.Column('midtrans_order_id', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('expired_at', sa.DateTime(), nullable=True))
    op.drop_constraint('payments_ref_code_key', 'payments', type_='unique')
    op.create_unique_constraint(None, 'payments', ['midtrans_order_id'])
    op.drop_column('payments', 'ref_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('ref_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'payments', type_='unique')
    op.create_unique_constraint('payments_ref_code_key', 'payments', ['ref_code'])
    op.drop_column('payments', 'expired_at')
    op.drop_column('payments', 'midtrans_order_id')
    op.drop_column('payments', 'payment_url')
    op.drop_column('payments', 'snap_token')
    # ### end Alembic commands ###
