"""add image_url to canteen and menu_item

Revision ID: 403dbc08c3ff
Revises: 9fbe89949e21
Create Date: 2026-04-07 17:35:55.981965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '403dbc08c3ff'
down_revision: Union[str, None] = '9fbe89949e21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('canteens', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('canteens', 'image_url')
    # ### end Alembic commands ###
