"""redesign_delivery_point_user_owned

Revision ID: 4f2e82d1354c
Revises: 
Create Date: 2026-04-05 08:16:44.084291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f2e82d1354c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_points', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('delivery_points', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('delivery_points', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('delivery_points', sa.Column('is_default', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'delivery_points', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'delivery_points', type_='foreignkey')
    op.drop_column('delivery_points', 'is_default')
    op.drop_column('delivery_points', 'longitude')
    op.drop_column('delivery_points', 'latitude')
    op.drop_column('delivery_points', 'user_id')
    # ### end Alembic commands ###
