"""add_categories_table

Revision ID: 924fd8fc0808
Revises: 4f2e82d1354c
Create Date: 2026-04-05 16:34:12.655142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '924fd8fc0808'
down_revision: Union[str, None] = '4f2e82d1354c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'menu_items', 'categories', ['category_id'], ['id'])
    op.drop_column('menu_items', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'menu_items', type_='foreignkey')
    op.drop_column('menu_items', 'category_id')
    # ### end Alembic commands ###
